### ISSUE TITLE
Volume /tmp

### ISSUE THREAD

**Issue by schmandr** [edigonzales/avdpool-camel#1]
Wozu wird `VOLUME /tmp` exposed? https://github.com/sogis/avdpool-camel/blob/dc3507b5a642ff1c87da759f783e13bd5713bc32/Dockerfile#L2

Müsste stattdessen nicht eher `/avdpool_data` exposed werden? Oder das vielleicht noch zusätzlich?

**Comment by edigonzales** [comment]
Keine Ahnung. Wohl copy/paste-Altlast.

Blöde Frage: muss man /avdpool_data exposen? "-v" funktioniert auch ohne.

**Comment by schmandr** [comment]
Muss nicht, ist aber empfehlenswert gemäss https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#volume:
>  You are strongly encouraged to use VOLUME for any mutable and/or user-serviceable parts of your image.

**Comment by schmandr** [comment]
Und platzier' doch gleich auch noch ein `EXPOSE 8888` ins Dockerfile. Auch dies ist kein Muss, aber OpenShift interpretiert das z.B. dann, wenn man mit `oc new-app ...` ein Image deployt. Dann erstellt es daraus gleich auch einen _Service_.

Gleichzeitig dient das auch der Dokumentation des Images.

**Comment by schmandr** [comment]
Ist unterdessen beides erledigt.
