### ISSUE TITLE
Fehlermeldungen in OpenShift

### ISSUE THREAD

**Issue by schmandr** [edigonzales/avdpool-camel#3]
Ich bringe die Anwendung in OpenShift nicht zum Laufen. Log (heikles Zeug durch Dummy-Zeug ersetzt): [avdpool-16-fwwxw_mod.log](https://github.com/sogis/avdpool-camel/files/3191665/avdpool-16-fwwxw_mod.log)

Liegt es an
`failed to create folder http://models.interlis.ch/ `
oder können keine Mails verschickt werden? Oder beides?

**Comment by edigonzales** [comment]
Beides. Aber keine E-Mails verschicken ist bloss die Folge davon. E-Mails werden nach Exceptions verschickt.

Bei mir im Docker-Container liegt der .ilicache-Ordner unter `/home/avdpool/.ilicache`. Kannst du das mal prüfen bei dir?

Notfalls kann man den ilicache-Ordner schon im ili2c via ENV-Variable steuern: https://github.com/claeis/ili2c/blob/b7d6ed2ab3ace4a4c4f1a980cf831ae6fd53ea29/src/ch/interlis/ilirepository/impl/RepositoryAccess.java#L70

**Comment by schmandr** [comment]
Nach https://github.com/sogis/avdpool-camel/commit/617948df2bd7ef3b776c497bcdfc6ec0e004dbfc kriege ich nun leider:
```
Picked up JAVA_TOOL_OPTIONS: 
Error: Could not find or load main class ch.so.agi.avdpool.AvdpoolApplication
Caused by: java.lang.ClassNotFoundException: ch.so.agi.avdpool.AvdpoolApplication
```

**Comment by schmandr** [comment]
Der Grund ist vielleicht, dass in der Zeile https://github.com/sogis/avdpool-camel/blob/c546fa2d71f540bdec1960d559988e12a83c7af4/Dockerfile#L20 das Verzeichnis `app` relativ gesucht wird. Und neu wird dann relativ zum neuen WORKDIR gesucht statt relativ zu `/`, so dass `/app` nun nicht mehr gefunden wird.

**Comment by schmandr** [comment]
Jetzt läuft die App, bringt aber wieder
`java.lang.IllegalArgumentException: failed to create folder http://models.interlis.ch/`

Problem ist wohl, dass `/home/avdpool` dem Benutzer _root_ gehört:
```
$ ls -la /home/avdpool
total 0
drwxr-xr-x. 1 root    root  17 May 20 10:38 .
drwxr-xr-x. 1 root    root  21 May 20 10:38 ..
drwxr-xr-x. 1 avdpool root 298 May 20 10:38 app
```
https://github.com/sogis/avdpool-camel/blob/bba0e9a70a7acf8c81c28fdaf45ce7674d6f15e8/Dockerfile#L13 ändern zu `RUN chown -R avdpool /home/avdpool`?

**Comment by schmandr** [comment]
Variante mit generischer User ID in https://github.com/sogis/avdpool-camel/pull/4. Ich konnte das Image aber nicht starten und testen. Könntest du das noch machen?

**Comment by schmandr** [comment]
Hat nun funktioniert.
E-Mails habe ich aber keine erhalten, obwohl ich die Dev-DB während des Imports absichtlich abgeschaltet habe. Hierfür mache ich dann mal einen separaten Issue.
