### ISSUE TITLE
E-Mail-Absenderadresse konfigurierbar machen

### ISSUE THREAD

**Issue by schmandr** [edigonzales/avdpool-camel#6]
Die Absenderadresse der bei Fehlern versendeten E-Mails lautet im Moment _camel@localhost_. Nützlich wäre, wenn man diese konfigurieren könnte. Inbesondere ab dann, wenn der Dienst in mehreren Umgebungen läuft, ist es sonst nicht mehr ersichtlich, in welcher Umgebung der Fehler aufgetreten ist.

In GRETL-Jenkins habe ich sie z.B. auf `GRETL Test <gretl-t@agi.so.ch>` gesetzt (das Feld heisst dort "System Admin e-mail address" und ist im Abschnitt "Jenkins Location")

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/avdpool-camel/commit/7e63a70f6559ee1c91f65f090575568d5fd9e7db

Es verwendet `emailUserSender` env Variable.
